### ISSUE TITLE
Your requirements.txt has a wrong nmap entry

### ISSUE THREAD

**Issue by dogasantos** [cybersecurityworks553/SolarWindsOrionScanner#1]
the correct one seems to be python3-nmap instead of nmap3:
pip install python3-nmap

reference: https://pypi.org/project/python3-nmap/

When trying to install using your requirements.txt, pip is not able to find codecs and nmap3

**Comment by dogasantos** [comment]
correction: python3-nmap doesnt seem to be the correct package.
Therefore, I'll create my own scan.
Thanks.

**Comment by cybersecurityworks553** [comment]
python3-nmap is the required package, Updated the requirements.txt accordingly.

**Comment by Teicu** [comment]
Hi, what is wrong there? 

_ERROR: Could not find a version that satisfies the requirement Requirements.txt (from versions: none)
ERROR: No matching distribution found for Requirements.txt_

**Comment by cybersecurityworks553** [comment]
The command to install requirements is: python3 -m pip install -r Requirements.txt
